#!/bin/sh
if [ -x "$HOME/.local/bin/spicetify-dsp-loopback.sh" ]; then
  "$HOME/.local/bin/spicetify-dsp-loopback.sh" >/dev/null 2>&1 || true
fi
npm run build && npm run build-local && spicetify apply
