#!/usr/bin/env node
/**
 * scripts/discover-modes.js
 * Scans `src/components/renderer/modes/` and automatically generates
 * `src/components/renderer/modes.generated.ts`.
 *
 * To disable or remove a mode:
 * - Delete the file in `modes/`
 * - OR move it into a `disabled/` subfolder
 * - OR rename it with `.disabled` (e.g. `solarCoronaEclipse.ts.disabled`)
 */

const fs = require("fs");
const path = require("path");

const MODES_DIR = path.resolve(__dirname, "../src/components/renderer/modes");
const OUTPUT_FILE = path.resolve(__dirname, "../src/components/renderer/modes.generated.ts");

function discoverModes() {
	if (!fs.existsSync(MODES_DIR)) {
		console.error(`[discover-modes] Directory not found: ${MODES_DIR}`);
		process.exit(1);
	}

	const entries = fs.readdirSync(MODES_DIR, { withFileTypes: true });

	const modeFiles = entries
		.filter(entry => {
			if (!entry.isFile()) return false;
			const name = entry.name;
			if (name.startsWith(".") || name.startsWith("_")) return false;
			if (name.includes(".disabled") || name.includes(".bak") || name.includes(".tmp")) return false;
			if (name.endsWith(".d.ts")) return false;
			return name.endsWith(".ts") || name.endsWith(".tsx");
		})
		.map(entry => entry.name)
		.sort();

	console.log(`[discover-modes] Found ${modeFiles.length} active mode(s):`);
	modeFiles.forEach(f => console.log(`  ✓ ${f}`));

	const imports = [];
	const modeVars = [];

	modeFiles.forEach((file, index) => {
		const basename = path.basename(file, path.extname(file));
		const varName = `mode_${index}_${basename.replace(/[^a-zA-Z0-9_]/g, "_")}`;
		imports.push(`import { modeConfig as ${varName} } from "./modes/${basename}";`);
		modeVars.push(varName);
	});

	const content = `// ============================================================================
// AUTO-GENERATED BY scripts/discover-modes.js - DO NOT EDIT MANUALLY
// Run "npm run discover" or "npm run build" to regenerate.
// ============================================================================

import React from "react";
import type { RendererDefinition } from "../../defs";
import { RENDERERS } from "../../defs";
import { createCanvasVisualizer, ModeConfig } from "./createCanvasVisualizer";

${imports.join("\n")}

export const ACTIVE_MODES: ModeConfig[] = [
${modeVars.map(v => `\t${v}`).join(",\n")}
];

export const GENERATED_RENDERERS: Record<string, RendererDefinition> = {};
export const GENERATED_RANDOM_VISUALIZERS: { id: string; name: string; Component: React.FunctionComponent<any> }[] = [];

for (const mode of ACTIVE_MODES) {
	if (!mode || !mode.id || !mode.name || !mode.render) continue;
	const Component = createCanvasVisualizer(mode.render, mode.name);
	const rendererDef: RendererDefinition = {
		name: mode.name,
		requiredAudioData: ["audioAnalysis", "extractedColor"],
		renderer: Component
	};
	GENERATED_RENDERERS[mode.id] = rendererDef;
	RENDERERS[mode.id] = rendererDef;
	if (mode.randomPool !== false) {
		GENERATED_RANDOM_VISUALIZERS.push({
			id: mode.id,
			name: mode.name,
			Component
		});
	}
}
`;

	fs.writeFileSync(OUTPUT_FILE, content, "utf-8");
	console.log(`[discover-modes] Successfully generated ${OUTPUT_FILE}`);
}

discoverModes();
