// ============================================================================
// AUTO-GENERATED BY scripts/discover-modes.js - DO NOT EDIT MANUALLY
// Run "npm run discover" or "npm run build" to regenerate.
// ============================================================================

import React from "react";
import type { RendererDefinition } from "../../defs";
import { RENDERERS } from "../../defs";
import { createCanvasVisualizer, ModeConfig } from "./createCanvasVisualizer";

import { modeConfig as mode_0_astralLotus } from "./modes/astralLotus";
import { modeConfig as mode_1_bigBang } from "./modes/bigBang";
import { modeConfig as mode_2_cosmicNebula } from "./modes/cosmicNebula";
import { modeConfig as mode_3_liquidSpectrum } from "./modes/liquidSpectrum";
import { modeConfig as mode_4_neonCat } from "./modes/neonCat";

export const ACTIVE_MODES: ModeConfig[] = [
	mode_0_astralLotus,
	mode_1_bigBang,
	mode_2_cosmicNebula,
	mode_3_liquidSpectrum,
	mode_4_neonCat
];

export const GENERATED_RENDERERS: Record<string, RendererDefinition> = {};
export const GENERATED_RANDOM_VISUALIZERS: { id: string; name: string; Component: React.FunctionComponent<any> }[] = [];

for (const mode of ACTIVE_MODES) {
	if (!mode || !mode.id || !mode.name || !mode.render) continue;
	const Component = createCanvasVisualizer(mode.render, mode.name);
	const rendererDef: RendererDefinition = {
		name: mode.name,
		requiredAudioData: ["audioAnalysis", "extractedColor"],
		renderer: Component
	};
	GENERATED_RENDERERS[mode.id] = rendererDef;
	RENDERERS[mode.id] = rendererDef;
	if (mode.randomPool !== false) {
		GENERATED_RANDOM_VISUALIZERS.push({
			id: mode.id,
			name: mode.name,
			Component
		});
	}
}
