// ============================================================================
// AUTO-GENERATED BY scripts/discover-modes.js - DO NOT EDIT MANUALLY
// Run "npm run discover" or "npm run build" to regenerate.
// ============================================================================

import React from "react";
import { RendererDefinition } from "../../defs";
import { createCanvasVisualizer, ModeConfig } from "./createCanvasVisualizer";

import { modeConfig as mode_0_astralLotus } from "./modes/astralLotus";
import { modeConfig as mode_1_bioluminescentJellyfish } from "./modes/bioluminescentJellyfish";
import { modeConfig as mode_2_cosmicNebula } from "./modes/cosmicNebula";

export const ACTIVE_MODES: ModeConfig[] = [
	mode_0_astralLotus,
	mode_1_bioluminescentJellyfish,
	mode_2_cosmicNebula
];

export const GENERATED_RENDERERS: Record<string, RendererDefinition> = {};
export const GENERATED_RANDOM_VISUALIZERS: { name: string; Component: React.FunctionComponent<any> }[] = [];

for (const mode of ACTIVE_MODES) {
	if (!mode || !mode.id || !mode.name || !mode.render) continue;
	const Component = createCanvasVisualizer(mode.render, mode.name);
	GENERATED_RENDERERS[mode.id] = {
		name: mode.name,
		requiredAudioData: ["audioAnalysis", "extractedColor"],
		renderer: Component
	};
	if (mode.randomPool !== false) {
		GENERATED_RANDOM_VISUALIZERS.push({
			name: mode.name,
			Component
		});
	}
}
